// Generated by ReScript, PLEASE EDIT WITH CARE

import * as IttyRouter from "itty-router";
import * as Caml_external_polyfill from "rescript/lib/es6/caml_external_polyfill.js";

var router = IttyRouter.Router();

router.get("/", (function (param) {
        return new Promise((function (resolve, param) {
                      return resolve(new Response("foo"));
                    }));
      }));

router.all("*", (function (param) {
        return new Promise((function (resolve, param) {
                      return resolve(new Response("Not found!"));
                    }));
      }));

Caml_external_polyfill.resolve("addEventListener")("fetch", (function (e) {
        e.respondWith(router.handle(e.request));
        
      }));

export {
  router ,
  
}
/* router Not a pure module */
